# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

gem 'opentelemetry-api', path: '../../api'
gem 'opentelemetry-common', path: '../../common'

group :test do
  gem 'opentelemetry-sdk', path: '../../sdk'
end
