# frozen_string_literal: true

source 'https://rubygems.org'

gem 'excon'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-instrumentation-excon', path: '../../../instrumentation/excon'
gem 'opentelemetry-sdk', path: '../../../sdk'
