# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-instrumentation-sidekiq', path: '../../../instrumentation/sidekiq'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-sdk', path: '../../../sdk'
