AllCops:
  TargetRubyVersion: "2.6.0"

Bundler/OrderedGems:
  Exclude:
    - "**/gemfiles/**/*"
Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "**/test/**/*"
Metrics/ParameterLists:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/opentelemetry-registry.rb"
Style/FrozenStringLiteralComment:
  Exclude:
    - "**/gemfiles/**/*"
Style/ModuleFunction:
  Enabled: false
Style/StringLiterals:
  Exclude:
    - "**/gemfiles/**/*"
    - "**/example/Gemfile"
