# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

eval_gemfile '../Gemfile'

group :test do
  gem 'appraisal', '~> 2.2.0'
  gem 'minitest', '~> 5.27.0'
  gem 'rspec-mocks', '~> 3.13.7'
  gem 'yard', '~> 0.9.0'
  gem 'yard-doctest', '~> 0.1.6'
  gem 'opentelemetry-api', path: '../api', require: false
end
