inherit_from: ../.rubocop-examples.yml

AllCops:
  Exclude:
    - test/railtie/dummy/**/*
    - gemfiles/*.gemfilqe

Metrics/BlockLength:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/opentelemetry-instrumentation-rails.rb"
Style/ClassAndModuleChildren:
  Exclude:
    - test/railtie/**/*
