# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

# Rails 5.2 is incompatible with Ruby 3.
if RUBY_VERSION < '3'
  appraise 'rails-5.2' do
    gem 'rails', '~> 5.2.0'
  end
end

appraise 'rails-6.0' do
  gem 'rails', '~> 6.0.0'
end

appraise 'rails-6.1' do
  gem 'rails', '~> 6.1.0'
end

if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.7.0')
  appraise 'rails-7.0' do
    gem 'rails', '~> 7.0.0.alpha2'
  end
end
