# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test, :development do
  # TODO: Uncomment
  # gem 'opentelemetry-instrumentation-action_pack', path: '../../instrumentation/action_pack'
  # gem 'opentelemetry-instrumentation-action_view', path: '../../instrumentation/action_view'
  # gem 'opentelemetry-instrumentation-active_record', path: '../../instrumentation/active_record'
  # gem 'opentelemetry-instrumentation-active_support', path: '../../instrumentation/active_support'
  # gem 'opentelemetry-instrumentation-base', path: '../base'
  # gem 'opentelemetry-instrumentation-rack', path: '../../instrumentation/rack'
  gem 'pry-byebug'
end
