# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

require 'bundler/gem_tasks'
require 'rake/testtask'
require 'yard'
require 'rubocop/rake_task'

RuboCop::RakeTask.new

namespace :test do
  Rake::TestTask.new :instrumentation do |t|
    t.libs << 'lib'
    t.libs << 'test/instrumentation'
    t.test_files = FileList['test/instrumentation/**/*_test.rb']
  end

  Rake::TestTask.new :railtie do |t|
    t.libs << 'lib'
    t.libs << 'test/railtie'
    t.test_files = FileList['test/railtie/**/*_test.rb']
  end
end

desc 'Run all tests'
task test: %i[test:instrumentation test:railtie]

YARD::Rake::YardocTask.new do |t|
  t.stats_options = ['--list-undoc']
end

if RUBY_ENGINE == 'truffleruby'
  task default: %i[test]
else
  task default: %i[test rubocop yard]
end
