# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/integration_test.proto for package 'integrationtest'
# Original file comments:
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
#

require 'grpc'
require_relative './integration_test_pb'

module Integrationtest
  module IntegrationTest
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'integrationtest.IntegrationTest'

      # Unary request/response
      rpc :EchoOne, ::Integrationtest::Message, ::Integrationtest::Message
      # Server-to-client stream
      rpc :EchoStream, ::Integrationtest::Message, stream(::Integrationtest::Message)
      # Client-to-server stream
      rpc :EchoMany, stream(::Integrationtest::Message), ::Integrationtest::Message
      # Client/Server bi-directional streaming
      rpc :EchoChat, stream(::Integrationtest::Message), stream(::Integrationtest::Message)
    end

    Stub = Service.rpc_stub_class
  end
end
