# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/integration_test.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/integration_test.proto", :syntax => :proto3) do
    add_message "integrationtest.Message" do
      optional :text, :string, 1
    end
  end
end

module Integrationtest
  Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("integrationtest.Message").msgclass
end
