# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

gem 'opentelemetry-api', path: '../../api'

gem 'rspec', '~>3'

group :test do
  gem 'opentelemetry-common', path: '../../common'
  gem 'opentelemetry-sdk', path: '../../sdk'
  gem 'opentelemetry-semantic_conventions', path: '../../semantic_conventions'
end
