# cSpell:ignore textlintrc
# For settings, see
# https://www.streetsidesoftware.com/vscode-spell-checker/docs/configuration/
version: "0.2"
caseSensitive: false
useGitignore: true
enableGlobDot: true
import:
  - https://cdn.jsdelivr.net/npm/@cspell/dict-people-names/cspell-ext.json
  - https://cdn.jsdelivr.net/npm/@cspell/dict-redis/cspell-ext.json
ignorePaths:
  - ".git"
  - "bin"
  - "CODEOWNERS"
  - "*.j2"
  - "*.thrift"
patterns:
  - name: CodeBlock
    pattern: |
      /
          ^(\s*[~`]{3,})   # code-block start
          .*               # all languages and options, e.g. shell {hl_lines=[12]}
          [\s\S]*?         # content
          \1               # code-block end
      /igmx
  - name: CodeName
    pattern: |
      /
          ([~`])          # Matches a single backtick or tilde to start a code block.
          [^~`]*?         # Matches any characters except backticks or tildes, non-greedy.
          \1              # Matches the same symbol which started the match.
      /x
  - name: "GitHub Handle"
    pattern: "@[a-zA-Z0-9-_]+\\b"
languageSettings:
  - languageId: json, jsonc
    includeRegExpList:
      - CStyleComment
  - languageId: markdown
    ignoreRegExpList:
      - CodeBlock
      - CodeName
      - GitHub Handle
  - languageId: ruby
    includeRegExpList:
      - "#.*/g"
    ignoreRegExpList:
      - CodeName
  - languageId: dockerfile, dockercompose, properties, yaml
    includeRegExpList:
      - "/#.*/g"
    ignoreRegExpList:
      - CodeName
dictionaries:
  - aws
  - companies
  - people-names
  - ruby
  - ruby-gems
  - softwareTerms
  - software-tools
  - redis
ignoreWords:
  - kwarg
  - MILLIS
  - otcorrelations
  - Rubyish
words:
  - LOGRECORD
  - traceid
  - tracestate
  - loggregator
  - configurator

  - autocorrection

  - linkspector
  - SARIF
