inherit_from:
  - ../contrib/rubocop.yml
  - .rubocop_todo.yml

Metrics/MethodLength:
  Max: 50
Metrics/PerceivedComplexity:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 20
Naming/FileName:
  Exclude:
    - "lib/opentelemetry-metrics-api.rb"
