# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'
eval_gemfile File.expand_path('../Gemfile', __dir__)

gemspec

group :test, :development do
  gem 'benchmark-ips', '~> 2.15.0'
  gem 'dotenv', '~> 3.2.0'
  gem 'minitest', '~> 6.0.0'
  gem 'simplecov', '~> 1.1.0'
  gem 'yard', '~> 0.9.0'
  gem 'yard-doctest', '~> 0.1.6'
  gem 'opentelemetry-api', path: '../api', require: false
  gem 'opentelemetry-metrics-sdk', path: '../metrics_sdk', require: false
  gem 'opentelemetry-test-helpers', path: '../test_helpers', require: false
end
