# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

gem 'opentelemetry-api', path: '../../api'
gem 'opentelemetry-common', path: '../../common'
gem 'opentelemetry-registry', path: '../registry'
gem 'opentelemetry-instrumentation-action_pack', path: '../action_pack'
gem 'opentelemetry-instrumentation-action_view', path: '../action_view'
gem 'opentelemetry-instrumentation-active_job', path: '../active_job'
gem 'opentelemetry-instrumentation-active_model_serializers', path: '../active_model_serializers'
gem 'opentelemetry-instrumentation-active_record', path: '../active_record'
gem 'opentelemetry-instrumentation-active_support', path: '../active_support'
gem 'opentelemetry-instrumentation-aws_sdk', path: '../aws_sdk'
gem 'opentelemetry-instrumentation-base', path: '../base'
gem 'opentelemetry-instrumentation-bunny', path: '../bunny'
gem 'opentelemetry-instrumentation-concurrent_ruby', path: '../concurrent_ruby'
gem 'opentelemetry-instrumentation-dalli', path: '../dalli'
gem 'opentelemetry-instrumentation-delayed_job', path: '../delayed_job'
gem 'opentelemetry-instrumentation-ethon', path: '../ethon'
gem 'opentelemetry-instrumentation-excon', path: '../excon'
gem 'opentelemetry-instrumentation-faraday', path: '../faraday'
gem 'opentelemetry-instrumentation-graphql', path: '../graphql'
gem 'opentelemetry-instrumentation-http', path: '../http'
gem 'opentelemetry-instrumentation-http_client', path: '../http_client'
gem 'opentelemetry-instrumentation-koala', path: '../koala'
gem 'opentelemetry-instrumentation-lmdb', path: '../lmdb'
gem 'opentelemetry-instrumentation-mongo', path: '../mongo'
gem 'opentelemetry-instrumentation-mysql2', path: '../mysql2'
gem 'opentelemetry-instrumentation-net_http', path: '../net_http'
gem 'opentelemetry-instrumentation-pg', path: '../pg'
gem 'opentelemetry-instrumentation-que', path: '../que'
gem 'opentelemetry-instrumentation-rack', path: '../rack'
gem 'opentelemetry-instrumentation-rails', path: '../rails'
gem 'opentelemetry-instrumentation-rdkafka', path: '../rdkafka'
gem 'opentelemetry-instrumentation-redis', path: '../redis'
gem 'opentelemetry-instrumentation-resque', path: '../resque'
gem 'opentelemetry-instrumentation-restclient', path: '../restclient'
gem 'opentelemetry-instrumentation-ruby_kafka', path: '../ruby_kafka'
gem 'opentelemetry-instrumentation-sidekiq', path: '../sidekiq'
gem 'opentelemetry-instrumentation-sinatra', path: '../sinatra'
gem 'opentelemetry-instrumentation-trilogy', path: '../trilogy'

group :test do
  gem 'active_model_serializers'
  gem 'activesupport'
  gem 'opentelemetry-sdk', path: '../../sdk'
  gem 'opentelemetry-semantic_conventions', path: '../../semantic_conventions'
end
