# frozen_string_literal: true

# Copyright 2019 OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

gem 'opentelemetry-api', path: '../../api'
gem 'opentelemetry-instrumentation-concurrent_ruby', path: '../concurrent_ruby'
gem 'opentelemetry-instrumentation-dalli', path: '../dalli'
gem 'opentelemetry-instrumentation-ethon', path: '../ethon'
gem 'opentelemetry-instrumentation-excon', path: '../excon'
gem 'opentelemetry-instrumentation-faraday', path: '../faraday'
gem 'opentelemetry-instrumentation-mysql2', path: '../mysql2'
gem 'opentelemetry-instrumentation-net_http', path: '../net_http'
gem 'opentelemetry-instrumentation-rack', path: '../rack'
gem 'opentelemetry-instrumentation-redis', path: '../redis'
gem 'opentelemetry-instrumentation-restclient', path: '../restclient'
gem 'opentelemetry-instrumentation-sidekiq', path: '../sidekiq'
gem 'opentelemetry-instrumentation-sinatra', path: '../sinatra'

group :test do
  gem 'opentelemetry-sdk', path: '../../sdk'
end
