inherit_from:
  - ../../contrib/rubocop.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - "thrift/**/*"
    - "vendor/**/*"

Metrics/ModuleLength:
  Max: 130
Metrics/MethodLength:
  Max: 25
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/opentelemetry-exporter-zipkin.rb"
Style/ExplicitBlockArgument:
  Enabled: false
