# frozen_string_literal: true

# Copyright 2020 OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'ruby-kafka-1.3.0' do
  gem 'ruby-kafka', '~> 1.3.0'
end

appraise 'ruby-kafka-1.2.0' do
  gem 'ruby-kafka', '~> 1.2.0'
end

appraise 'ruby-kafka-1.1.0' do
  gem 'ruby-kafka', '~> 1.1.0'
end

appraise 'ruby-kafka-1.0.0' do
  gem 'ruby-kafka', '~> 1.0.0'
end
