# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: opentelemetry/proto/collector/trace/v1/trace_service.proto for package 'opentelemetry.proto.collector.trace.v1'
# Original file comments:
# Copyright 2019, OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require 'opentelemetry/proto/collector/trace/v1/trace_service_pb'

module Opentelemetry
  module Proto
    module Collector
      module Trace
        module V1
          module TraceService
            # Service that can be used to push spans between one Application instrumented with
            # OpenTelemetry and a collector, or between a collector and a central collector (in this
            # case spans are sent/received to/from multiple Applications).
            class Service

              include GRPC::GenericService

              self.marshal_class_method = :encode
              self.unmarshal_class_method = :decode
              self.service_name = 'opentelemetry.proto.collector.trace.v1.TraceService'

              # For performance reasons, it is recommended to keep this RPC
              # alive for the entire life of the application.
              rpc :Export, ::Opentelemetry::Proto::Collector::Trace::V1::ExportTraceServiceRequest, ::Opentelemetry::Proto::Collector::Trace::V1::ExportTraceServiceResponse
            end

            Stub = Service.rpc_stub_class
          end
        end
      end
    end
  end
end
