# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'lmdb-0.5' do
  gem 'lmdb', '~> 0.5.0'
end

appraise 'lmdb-0.4' do
  gem 'lmdb', '~> 0.4.0'
end
