# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/logs/v1/logs.proto

require 'google/protobuf'

require 'opentelemetry/proto/common/v1/common_pb'
require 'opentelemetry/proto/resource/v1/resource_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("opentelemetry/proto/logs/v1/logs.proto", :syntax => :proto3) do
    add_message "opentelemetry.proto.logs.v1.LogsData" do
      repeated :resource_logs, :message, 1, "opentelemetry.proto.logs.v1.ResourceLogs"
    end
    add_message "opentelemetry.proto.logs.v1.ResourceLogs" do
      optional :resource, :message, 1, "opentelemetry.proto.resource.v1.Resource"
      repeated :scope_logs, :message, 2, "opentelemetry.proto.logs.v1.ScopeLogs"
      optional :schema_url, :string, 3
    end
    add_message "opentelemetry.proto.logs.v1.ScopeLogs" do
      optional :scope, :message, 1, "opentelemetry.proto.common.v1.InstrumentationScope"
      repeated :log_records, :message, 2, "opentelemetry.proto.logs.v1.LogRecord"
      optional :schema_url, :string, 3
    end
    add_message "opentelemetry.proto.logs.v1.LogRecord" do
      optional :time_unix_nano, :fixed64, 1
      optional :observed_time_unix_nano, :fixed64, 11
      optional :severity_number, :enum, 2, "opentelemetry.proto.logs.v1.SeverityNumber"
      optional :severity_text, :string, 3
      optional :body, :message, 5, "opentelemetry.proto.common.v1.AnyValue"
      repeated :attributes, :message, 6, "opentelemetry.proto.common.v1.KeyValue"
      optional :dropped_attributes_count, :uint32, 7
      optional :flags, :fixed32, 8
      optional :trace_id, :bytes, 9
      optional :span_id, :bytes, 10
    end
    add_enum "opentelemetry.proto.logs.v1.SeverityNumber" do
      value :SEVERITY_NUMBER_UNSPECIFIED, 0
      value :SEVERITY_NUMBER_TRACE, 1
      value :SEVERITY_NUMBER_TRACE2, 2
      value :SEVERITY_NUMBER_TRACE3, 3
      value :SEVERITY_NUMBER_TRACE4, 4
      value :SEVERITY_NUMBER_DEBUG, 5
      value :SEVERITY_NUMBER_DEBUG2, 6
      value :SEVERITY_NUMBER_DEBUG3, 7
      value :SEVERITY_NUMBER_DEBUG4, 8
      value :SEVERITY_NUMBER_INFO, 9
      value :SEVERITY_NUMBER_INFO2, 10
      value :SEVERITY_NUMBER_INFO3, 11
      value :SEVERITY_NUMBER_INFO4, 12
      value :SEVERITY_NUMBER_WARN, 13
      value :SEVERITY_NUMBER_WARN2, 14
      value :SEVERITY_NUMBER_WARN3, 15
      value :SEVERITY_NUMBER_WARN4, 16
      value :SEVERITY_NUMBER_ERROR, 17
      value :SEVERITY_NUMBER_ERROR2, 18
      value :SEVERITY_NUMBER_ERROR3, 19
      value :SEVERITY_NUMBER_ERROR4, 20
      value :SEVERITY_NUMBER_FATAL, 21
      value :SEVERITY_NUMBER_FATAL2, 22
      value :SEVERITY_NUMBER_FATAL3, 23
      value :SEVERITY_NUMBER_FATAL4, 24
    end
    add_enum "opentelemetry.proto.logs.v1.LogRecordFlags" do
      value :LOG_RECORD_FLAGS_DO_NOT_USE, 0
      value :LOG_RECORD_FLAGS_TRACE_FLAGS_MASK, 255
    end
  end
end

module Opentelemetry
  module Proto
    module Logs
      module V1
        LogsData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.logs.v1.LogsData").msgclass
        ResourceLogs = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.logs.v1.ResourceLogs").msgclass
        ScopeLogs = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.logs.v1.ScopeLogs").msgclass
        LogRecord = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.logs.v1.LogRecord").msgclass
        SeverityNumber = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.logs.v1.SeverityNumber").enummodule
        LogRecordFlags = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.logs.v1.LogRecordFlags").enummodule
      end
    end
  end
end
