# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test, :development do
  gem 'opentelemetry-sdk', path: '../../sdk'
  gem 'opentelemetry-instrumentation-base', path: '../base'
end
