# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'http-4.4' do
  gem 'http', '~> 4.4.0'
end

appraise 'http-3.3.0' do
  gem 'http', '~> 3.3.0'
end
