inherit_from:
  - ../../contrib/rubocop.yml
  - .rubocop_todo.yml

Metrics/BlockLength:
  Exclude:
    - 'opentelemetry-propagator-jaeger.gemspec'
    - 'test/**/*_test.rb'
Naming/FileName:
  Exclude:
    - 'lib/opentelemetry-propagator-jaeger.rb'
