# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'opentelemetry-api', path: '../../api'
  gem 'opentelemetry-common', path: '../../common'
  gem 'opentelemetry-registry', path: '../../registry'
  gem 'opentelemetry-sdk', path: '../../sdk'
end
