inherit_from: ../../contrib/rubocop.yml

AllCops:
  Exclude:
    - "lib/opentelemetry/proto/**/*"
    - "vendor/**/*"

Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/opentelemetry-exporter-otlp-http.rb"
