# frozen_string_literal: true

# Copyright 2019 OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

require 'bundler/gem_tasks'
require 'rake/testtask'
require 'yard'

require 'rubocop/rake_task'
RuboCop::RakeTask.new

Rake::TestTask.new :test do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.libs << '../api/lib'
  t.test_files = FileList['test/**/*_test.rb']
end

YARD::Rake::YardocTask.new do |t|
  files = Dir.glob('./lib/**/*.rb')

  # Move ./lib/opentelemetry/opentracingshim.rb to the end of the array.
  # Otherwise other files will overwrite the OpenTelemetryShim module
  # comments with the license information.
  ots_index = files.index('./lib/opentelemetry/opentracingshim.rb')
  files = files.insert(-1, files.delete_at(ots_index))

  t.files = files # optional
  t.options = ['--output-dir', 'docs/opentracingshim'] # optional
  t.stats_options = ['--list-undoc'] # optional
end

if RUBY_ENGINE == 'truffleruby'
  task default: %i[test]
else
  task default: %i[test rubocop yard]
end
