# frozen_string_literal: true

source 'https://rubygems.org'

gem 'ethon'
gem 'opentelemetry-instrumentations-ethon', path: '../../../instrumentations/ethon'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-sdk', path: '../../../sdk'
