# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-instrumentations-net_http', path: '../../../instrumentations/net_http'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-sdk', path: '../../../sdk'
