AllCops:
  TargetRubyVersion: "2.6.0"

Lint/UnusedMethodArgument:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 21
Metrics/ParameterLists:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/opentelemetry-test-helpers.rb"
Style/ModuleFunction:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false
