# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

# Use the opentelemetry-api gem from source

group :test, :development do
  gem 'opentelemetry-api', path: '../api'
  gem 'opentelemetry-common', path: '../common'
  gem 'opentelemetry-exporter-zipkin', path: '../exporter/zipkin'
  gem 'opentelemetry-instrumentation-base', path: '../instrumentation/base'
  gem 'opentelemetry-registry', path: '../registry'
  gem 'opentelemetry-semantic_conventions', path: '../semantic_conventions'
end
