# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

# Use the opentelemetry-api gem from source
gem 'opentelemetry-api', path: '../../api'
gem 'opentelemetry-common', path: '../../common'
gem 'opentelemetry-exporter-otlp-common', path: '../otlp-common'
gem 'opentelemetry-instrumentation-base', path: '../../instrumentation/base'
gem 'opentelemetry-sdk', path: '../../sdk'

group :test, :development do
  gem 'opentelemetry-test-helpers', path: '../../test_helpers'
end
