# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test, :development do
  gem 'opentelemetry-api', path: '../../api'
  gem 'opentelemetry-exporter-otlp-common', path: '../otlp-common'
  gem 'opentelemetry-registry', path: '../../registry'
  gem 'opentelemetry-sdk', path: '../../sdk'
  gem 'opentelemetry-semantic_conventions', path: '../../semantic_conventions'
  gem 'opentelemetry-test-helpers', path: '../../test_helpers'
end
