# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-adapters-rack', path: '../../../adapters/rack'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-sdk', path: '../../../sdk'
gem 'rack'
gem 'rack-test'
