# frozen_string_literal: true

appraise 'sidekiq-6.5' do
  gem 'sidekiq', '~> 6.5'
end

appraise 'sidekiq-6.4' do
  gem 'sidekiq', '~> 6.4'
end

appraise 'sidekiq-6.3' do
  gem 'sidekiq', '~> 6.3'
end

appraise 'sidekiq-6.1' do
  gem 'sidekiq', '~> 6.1'
end

appraise 'sidekiq-6.0' do
  gem 'sidekiq', '~> 6.0'
end

appraise 'sidekiq-5.2' do
  gem 'sidekiq', '~> 5.2'
end

appraise 'sidekiq-4.2' do
  gem 'sidekiq', '~> 4.2'
end
