# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

gem 'opentelemetry-api', path: '../../api'

group :test do
  gem 'pry'
  gem 'pry-byebug'
  gem 'fakeredis', require: 'fakeredis/minitest'
  gem 'opentelemetry-instrumentation-redis'
  gem 'opentelemetry-common', path: '../../common'
  gem 'opentelemetry-sdk', path: '../../sdk'
end
