# frozen_string_literal: true

# Copyright 2020 OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'rails-6.0' do
  gem 'rails', '6.0.2.2'
end

appraise 'rails-5.2' do
  gem 'rails', '5.2.4.2'
end
