# frozen_string_literal: true

# Copyright 2019 OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

gem 'opentelemetry-api', path: '../../api'
gem 'opentelemetry-adapters-rack', path: '../../adapters/rack'

group :test do
  gem 'opentelemetry-sdk', path: '../../sdk'
end
