# Copyright 2019 OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

version: 2.1
executors:
  ruby24:
    docker:
      - image: "circleci/ruby:2.4-stretch"
  ruby25:
    docker:
      - image: "circleci/ruby:2.5-stretch"
  ruby26:
    docker:
      - image: "circleci/ruby:2.6-stretch"
  jruby:
    docker:
      - image: "circleci/jruby:latest"
    environment:
      JRUBY_OPTS: "--debug"
commands:
  rake:
    parameters:
      dir:
        type: string
      task:
        type: string
        default: default
    steps:
      - checkout
      - run:
          name: Bundle
          command: "cd << parameters.dir >> && gem install --no-document bundler && bundle install --jobs=3 --retry=3"
      - run:
          name: CI
          command: "cd << parameters.dir >> && bundle exec rake << parameters.task >>"
jobs:
  test-api-ruby24:
    executor: ruby24
    steps:
      - rake:
          dir: api
  test-api-ruby25:
    executor: ruby25
    steps:
      - rake:
          dir: api
  test-api-ruby26:
    executor: ruby26
    steps:
      - rake:
          dir: api
  test-api-jruby:
    executor: jruby
    steps:
      - rake:
          dir: api
  test-sdk-ruby24:
    executor: ruby24
    steps:
      - rake:
          dir: sdk
  test-sdk-ruby25:
    executor: ruby25
    steps:
      - rake:
          dir: sdk
  test-sdk-ruby26:
    executor: ruby26
    steps:
      - rake:
          dir: sdk
  test-sdk-jruby:
    executor: jruby
    steps:
      - rake:
          dir: sdk
  release-api:
    executor: ruby26
    steps:
      - rake:
          dir: api
          task: push_release
  release-sdk:
    executor: ruby26
    steps:
      - rake:
          dir: sdk
          task: push_release
workflows:
  version: 2
  builds:
    jobs:
      - test-api-ruby24:
          filters:
            tags:
              only: /^opentelemetry-api\/v\d.*$/
      - test-api-ruby25:
          filters:
            tags:
              only: /^opentelemetry-api\/v\d.*$/
      - test-api-ruby26:
          filters:
            tags:
              only: /^opentelemetry-api\/v\d.*$/
      - test-api-jruby:
          filters:
            tags:
              only: /^opentelemetry-api\/v\d.*$/
      - test-sdk-ruby24:
          filters:
            tags:
              only: /^opentelemetry-sdk\/v\d.*$/
      - test-sdk-ruby25:
          filters:
            tags:
              only: /^opentelemetry-sdk\/v\d.*$/
      - test-sdk-ruby26:
          filters:
            tags:
              only: /^opentelemetry-sdk\/v\d.*$/
      - test-sdk-jruby:
          filters:
            tags:
              only: /^opentelemetry-sdk\/v\d.*$/
      - release-api:
          requires:
            - test-api-ruby24
            - test-api-ruby25
            - test-api-ruby26
            - test-api-jruby
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^opentelemetry-api\/v\d.*$/
      - release-sdk:
          requires:
            - test-sdk-ruby24
            - test-sdk-ruby25
            - test-sdk-ruby26
            - test-sdk-jruby
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^opentelemetry-sdk\/v\d.*$/
