# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'
eval_gemfile File.expand_path('../Gemfile', __dir__)

gemspec

group :test, :development do
  gem 'minitest', '~> 6.0.0'
  gem 'simplecov', '~> 0.22.0'
  gem 'webmock', '~> 3.24'
  gem 'yard', '~> 0.9.0'
  gem 'yard-doctest', '~> 0.1.6'
  gem 'opentelemetry-test-helpers', path: '../../test_helpers', require: false
end
