# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

require 'bundler/gem_tasks'
require 'rake/testtask'
require 'yaml'
require 'yard'

require 'rubocop/rake_task'
RuboCop::RakeTask.new
YARD::Rake::YardocTask.new

Rake::TestTask.new :test do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['test/**/*_test.rb']
end

default_tasks =
  if RUBY_ENGINE == 'truffleruby'
    %i[test]
  else
    %i[test rubocop yard]
  end

task default: default_tasks

OTEL_SPECS = YAML.load_file('otel-spec.yaml').freeze
PROTO_VERSION = OTEL_SPECS['opentelemetry-proto'].freeze
PROTOBUF_FILES = [
  'collector/logs/v1/logs_service.proto',
  'collector/metrics/v1/metrics_service.proto',
  'collector/trace/v1/trace_service.proto',
  'common/v1/common.proto',
  'logs/v1/logs.proto',
  'metrics/v1/metrics.proto',
  'resource/v1/resource.proto',
  'trace/v1/trace.proto'
].freeze

desc 'Generate probobuf'
task :generate do
  run("git clone -b v#{PROTO_VERSION} https://github.com/open-telemetry/opentelemetry-proto")
  PROTOBUF_FILES.each do |file|
    run("protoc --ruby_out=lib/ --proto_path=opentelemetry-proto opentelemetry/proto/#{file}")
  end
  run('rm -rf opentelemetry-proto')
end

def run(cmd)
  puts "#{cmd}"
  IO.popen(cmd) do |io|
    io.each_line { |line| puts line }
  end
  raise "Command failed: #{cmd}" unless $?.success?
end

