---
AllCops:
  TargetRubyVersion: '2.5.0'
Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Max: 18
Metrics/BlockLength:
  Exclude:
    - 'test/opentelemetry/propagator/**/*_test.rb'
    - 'opentelemetry-propagator-ottrace.gemspec'
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/ParameterLists:
  Enabled: false
Naming/FileName:
  Exclude:
    - 'lib/opentelemetry-propagator-ottrace.rb'
Style/ModuleFunction:
  Enabled: false
