# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in opentelemetry-propragator-ottrace.gemspec
gemspec

gem 'opentelemetry-api', path: '../../api'
gem 'opentelemetry-sdk', path: '../../sdk'
gem 'opentelemetry-common', path: '../../common'
