# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bunny'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-instrumentation-bunny', path: '../../../instrumentation/bunny'
gem 'opentelemetry-sdk', path: '../../../sdk'
