# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

## TODO: Include the supported version to be tested here.
# appraise 'rdkafka' do
#   gem 'rdkafka', '0.10.0'
# end
