# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

# 0.10.0 is the current version at the time of instrumentation creation
appraise 'rdkafka-0.10.0' do
  gem 'rdkafka', '0.10.0'
end
