# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
# This file was autogenerated. Do not edit it by hand.

module OpenTelemetry
  module SemConv
    module Incubating
      module GEN_AI
        # @!group Event Names

        # This event describes the assistant message passed to GenAI system.
        #
        # @note Stability Level: development
        # @deprecated Chat history is reported on `gen_ai.input.messages` attribute on spans or `gen_ai.client.inference.operation.details` event.
        GEN_AI_ASSISTANT_MESSAGE = 'gen_ai.assistant.message'

        # This event describes the Gen AI response message.
        #
        # @note Stability Level: development
        # @deprecated Chat history is reported on `gen_ai.output.messages` attribute on spans or `gen_ai.client.inference.operation.details` event.
        GEN_AI_CHOICE = 'gen_ai.choice'

        # Describes the details of a GenAI completion request including chat history and parameters.
        #
        # This event is opt-in and could be used to store input and output details independently from traces.
        #
        # @note Stability Level: development
        GEN_AI_CLIENT_INFERENCE_OPERATION_DETAILS = 'gen_ai.client.inference.operation.details'

        # This event describes the system instructions passed to the GenAI model.
        #
        # @note Stability Level: development
        # @deprecated Chat history is reported on `gen_ai.system_instructions` attribute on spans or `gen_ai.client.inference.operation.details` event.
        GEN_AI_SYSTEM_MESSAGE = 'gen_ai.system.message'

        # This event describes the response from a tool or function call passed to the GenAI model.
        #
        # @note Stability Level: development
        # @deprecated Chat history is reported on `gen_ai.input.messages` attribute on spans or `gen_ai.client.inference.operation.details` event.
        GEN_AI_TOOL_MESSAGE = 'gen_ai.tool.message'

        # This event describes the user message passed to the GenAI model.
        #
        # @note Stability Level: development
        # @deprecated Chat history is reported on `gen_ai.input.messages` attribute on spans or `gen_ai.client.inference.operation.details` event.
        GEN_AI_USER_MESSAGE = 'gen_ai.user.message'

        # @!endgroup
      end
    end
  end
end
