# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

eval_gemfile '../../Gemfile'

group :test, :development do
  gem 'appraisal', '~> 2.2.0'
  gem 'minitest', '~> 5.27.0'
  gem 'webmock', '~> 3.24'
  gem 'yard', '~> 0.9.0'
  gem 'yard-doctest', '~> 0.1.6'
  gem 'opentelemetry-api', path: '../../api', require: false
  gem 'opentelemetry-common', path: '../../common', require: false
  gem 'opentelemetry-logs-api', path: '../../logs_api', require: false
  gem 'opentelemetry-logs-sdk', path: '../../logs_sdk', require: false
  gem 'opentelemetry-registry', path: '../../registry', require: false
  gem 'opentelemetry-sdk', path: '../../sdk', require: false
  gem 'opentelemetry-semantic_conventions', path: '../../semantic_conventions', require: false
  gem 'opentelemetry-test-helpers', path: '../../test_helpers', require: false
end

group :test do
  gem 'minitest-stub-const'
end
