inherit_from: ../../contrib/rubocop.yml

AllCops:
  Exclude:
    - "lib/opentelemetry/proto/**/*"
    - "vendor/**/*"

Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Bundler/OrderedGems:
  Exclude:
    - gemfiles/**/*
Style/FrozenStringLiteralComment:
  Exclude:
    - gemfiles/**/*
Style/ModuleFunction:
  Enabled: false
Style/StringLiterals:
  Exclude:
    - gemfiles/**/*
Metrics/BlockLength:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/opentelemetry-exporter-otlp-metrics.rb"
