# frozen_string_literal: true

source 'https://rubygems.org'

gem 'excon'
gem 'opentelemetry-instrumentations-excon', path: '../../../instrumentations/excon'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-sdk', path: '../../../sdk'
