# frozen_string_literal: true

source 'https://rubygems.org'

gem 'concurrent-ruby'
gem 'opentelemetry-adapters-concurrent-ruby', path: '../../../adapters/concurrent-ruby'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-sdk', path: '../../../sdk'
