# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
# This file was autogenerated. Do not edit it by hand.

module OpenTelemetry
  module SemConv
  module Incubating
    module MESSAGE
      # @!group Attribute Names
    
      # Compressed size of the message in bytes
      #
      # @note StabilityLevel.EXPERIMENTAL
      MESSAGE_COMPRESSED_SIZE = 'message.compressed_size'
  
      # MUST be calculated as two different counters starting from `1` one for sent messages and one for received message
      #
      # This way we guarantee that the values will be consistent between different implementations
      #
      # @note StabilityLevel.EXPERIMENTAL
      MESSAGE_ID = 'message.id'
  
      # Whether this is a received or sent message
      #
      # @note StabilityLevel.EXPERIMENTAL
      MESSAGE_TYPE = 'message.type'
  
      # Uncompressed size of the message in bytes
      #
      # @note StabilityLevel.EXPERIMENTAL
      MESSAGE_UNCOMPRESSED_SIZE = 'message.uncompressed_size'
  
      # @!endgroup

      # @!group Metric Names
      # @!endgroup
    end
  end # module Incubating
  end
end