# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

## Example:
# appraise 'rack-2.1' do
#   gem 'rack', '~> 2.1.2'
# end

appraise 'elasticsearch-8.0' do
  gem 'elasticsearch', '~> 8.0'
end
