# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

require 'bundler/gem_tasks'
require 'English'
require 'rake/testtask'
require 'yaml'
require 'yard'

require 'rubocop/rake_task'
RuboCop::RakeTask.new
YARD::Rake::YardocTask.new

Rake::TestTask.new :test do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.libs << '../../api/lib'
  t.libs << '../../sdk/lib'
  t.test_files = FileList['test/**/*_test.rb']
end

default_tasks =
  if RUBY_ENGINE == 'truffleruby'
    %i[test]
  else
    %i[test rubocop yard]
  end

task default: default_tasks


OTEL_SPECS = YAML.load_file('otel-spec.yaml').freeze
PROTO_VERSION = OTEL_SPECS['opentelemetry-proto'].freeze

desc 'Generate probobuf'
task :generate do
  FileUtils.rm_rf('lib/opentelemetry/proto')
  FileUtils.rm_rf('opentelemetry-proto')
  run("git clone -b v#{PROTO_VERSION} https://github.com/open-telemetry/opentelemetry-proto")
  run("grpc_tools_ruby_protoc --grpc_out=lib --proto_path=opentelemetry-proto opentelemetry/proto/collector/trace/v1/trace_service.proto")
  FileUtils.rm_rf('opentelemetry-proto')
end

def run(cmd)
  puts cmd
  IO.popen(cmd) do |io|
    io.each_line { |line| puts line }
  end
  raise "Command failed: #{cmd}" unless $CHILD_STATUS.success?
end