# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-instrumentations-redis', path: '../../../instrumentations/redis'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-sdk', path: '../../../sdk'
gem 'redis'
