name: 'Test steps'
description: 'Test steps'
runs:
  using: "composite"
  services:
    sql:
      image: mysql:5.6
      env:
        TEST_MYSQL_USER: root
        TEST_MYSQL_ROOT_PASSWORD: root
        TEST_MYSQ_DB: mysql
        MYSQL_DATABASE: mysql
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: mysql
        MYSQL_USER: mysql
      ports:
        - 3306
      options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
  steps:
    - name: rake-test
      run: ./ci/rake_test.sh
    - name: rake-test-appraisal
      run: ./ci/rake_test_appraisal.sh
    - name: rake-test-appraisal-container-ints
      env:
        TEST_MYSQL_HOST: sql
        TEST_MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
      run: ./ci/rake_test_appraisal_container_ints.sh
