AllCops:
  TargetRubyVersion: "2.4.0"
  Exclude:
    - "thrift/**/*"

Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Max: 18
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/ParameterLists:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/opentelemetry-exporters-jaeger.rb"
Style/ModuleFunction:
  Enabled: false
