# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-instrumentation-dalli', path: '../../../instrumentation/dalli'
gem 'opentelemetry-sdk', path: '../../../sdk'
gem 'dalli'
