inherit_from: ../contrib/rubocop.yml

Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 50
Metrics/PerceivedComplexity:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 20
Naming/FileName:
  Exclude:
    - "lib/opentelemetry-metrics-sdk.rb"
Lint/AmbiguousOperatorPrecedence:
  Enabled: false
Lint/AmbiguousRange:
  Enabled: false
Naming/BlockForwarding:
  Enabled: false
Naming/PredicateMethod:
  Enabled: false
Performance/CollectionLiteralInLoop:
  Enabled: false
Style/ArgumentsForwarding:
  Enabled: false
Style/CollectionQuerying:
  Enabled: false
Style/EmptyClassDefinition:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
Style/MapIntoArray:
  Enabled: false
Style/NilLambda:
  Enabled: false
Style/SuperArguments:
  Enabled: false
Lint/SymbolConversion:
  Enabled: false
