inherit_from: ../contrib/rubocop.yml

Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 50
Metrics/PerceivedComplexity:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 20
Style/ArgumentsForwarding:
  Enabled: false
Style/CollectionQuerying:
  Enabled: false
Style/EmptyClassDefinition:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
Style/MapIntoArray:
  Enabled: false
Style/NilLambda:
  Enabled: false
Style/SuperArguments:
  Enabled: false
