# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

eval_gemfile '../contrib/Gemfile.shared'

group :test, :development do
  gem 'opentelemetry-api', path: '../api', require: false
  gem 'opentelemetry-common', path: '../common', require: false
  gem 'opentelemetry-exporter-otlp-metrics', path: '../exporter/otlp-metrics', require: false unless RUBY_ENGINE == 'jruby'
  gem 'opentelemetry-metrics-api', path: '../metrics_api', require: false
  gem 'opentelemetry-registry', path: '../registry', require: false
  gem 'opentelemetry-sdk', path: '../sdk', require: false
  gem 'opentelemetry-test-helpers', path: '../test_helpers', require: false
  gem 'pry'
  gem 'pry-byebug' unless RUBY_ENGINE == 'jruby'
end
