# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

gem 'opentelemetry-api', path: '../api'
gem 'opentelemetry-common', path: '../common'
gem 'opentelemetry-metrics-api', path: '../metrics_api'
gem 'opentelemetry-registry', path: '../registry'
gem 'opentelemetry-sdk', path: '../sdk'
gem 'opentelemetry-test-helpers', path: '../test_helpers'

group :test, :development do
  gem 'opentelemetry-exporter-otlp-metrics', path: '../exporter/otlp-metrics' unless RUBY_ENGINE == 'jruby'
  gem 'pry'
  gem 'pry-byebug' unless RUBY_ENGINE == 'jruby'
end
