# frozen_string_literal: true

source 'https://rubygems.org'

gem 'graphql'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-instrumentation-graphql', path: '../../../instrumentation/graphql'
gem 'opentelemetry-sdk', path: '../../../sdk'
