# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-api'
gem 'opentelemetry-common'
gem 'opentelemetry-instrumentation-concurrent_ruby'
gem 'opentelemetry-sdk'

gem 'rspec'
