# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-instrumentations-restclient', path: '../../../instrumentations/restclient'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-sdk', path: '../../../sdk'
gem 'rest-client'
