# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-common', path: '../../../common'
gem 'opentelemetry-instrumentation-redis', path: '../../../instrumentation/redis'
gem 'opentelemetry-sdk', path: '../../../sdk'
gem 'redis'
