# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'
eval_gemfile File.expand_path('../Gemfile', __dir__)

gemspec

group :test, :development do
  gem 'minitest', '6.0.6'
  gem 'simplecov', '1.0.0'
  gem 'yard', '0.9.45'

  # Local path overrides for gems developed in this monorepo
  gem 'opentelemetry-exporter-otlp-common',      path: '../exporter/otlp-common',      require: false
  gem 'opentelemetry-registry',                  path: '../registry',                  require: false
  gem 'opentelemetry-test-helpers',              path: '../test_helpers',              require: false

  gem 'opentelemetry-propagator-google_cloud_trace_context',    '0.4.0'
  gem 'opentelemetry-propagator-ottrace',                       '0.25.0'
  gem 'opentelemetry-propagator-xray',                          '0.27.0'
  gem 'opentelemetry-resource-detector-aws',                    '0.7.0'
  gem 'opentelemetry-resource-detector-azure',                  '0.4.0'
  gem 'opentelemetry-resource-detector-container',              '0.4.0'
  gem 'opentelemetry-resource-detector-google_cloud_platform',  '0.4.0'

  # Prevent bundler from downgrading google-protobuf to an incompatible
  # pre-built binary (glibc) that does not run in Alpine (musl) containers.
  gem 'google-protobuf', '3.25.8'

  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'bigdecimal'
    gem 'mutex_m'
  end
  gem 'logger' if RUBY_VERSION >= '4.0.0'
end
