# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-instrumentation-net_http', path: '../../../instrumentation/net_http'
gem 'opentelemetry-common', path: '../../../common'
gem 'opentelemetry-sdk', path: '../../../sdk'
