# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
# This file was autogenerated. Do not edit it by hand.

module OpenTelemetry
  module SemConv
    module Incubating
      module APP
        # @!group Event Names

        # This event indicates that the application has detected substandard UI rendering performance.
        #
        # Jank happens when the UI is rendered slowly enough for the user to experience some disruption or sluggishness.
        #
        # @note Stability Level: development
        APP_JANK = 'app.jank'

        # This event represents an instantaneous click on the screen of an application.
        #
        # The `app.screen.click` event can be used to indicate that a user has clicked or tapped on the screen portion of an application. Clicks outside of an application's active area SHOULD NOT generate this event. This event does not differentiate between touch/mouse down and touch/mouse up. Implementations SHOULD give preference to generating this event at the time the click is complete, typically on touch release or mouse up. The location of the click event MUST be provided in absolute screen pixels.
        #
        # @note Stability Level: development
        APP_SCREEN_CLICK = 'app.screen.click'

        # This event indicates that an application widget has been clicked.
        #
        # Use this event to indicate that visual application component has been clicked, typically through a user's manual interaction.
        #
        # @note Stability Level: development
        APP_WIDGET_CLICK = 'app.widget.click'

        # @!endgroup
      end
    end
  end
end
