AllCops:
  TargetRubyVersion: '2.6.0'
Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/ParameterLists:
  Enabled: false
Naming/FileName:
  Exclude:
    - 'lib/opentelemetry-propagator-b3.rb'
Style/ModuleFunction:
  Enabled: false
