# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'
eval_gemfile File.expand_path('../../Gemfile', __dir__)

gemspec

group :test, :development do
  gem 'minitest', '~> 6.0.0'
  gem 'simplecov', '~> 1.1.0'
  gem 'yard', '~> 0.9.0'
  gem 'yard-doctest', '~> 0.1.6'
  gem 'opentelemetry-api', path: '../../api', require: false
end
