# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-api'
gem 'opentelemetry-common'
gem 'opentelemetry-instrumentation-restclient'
gem 'opentelemetry-sdk'
gem 'rest-client'
