# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-instrumentation-rack', path: '../../../instrumentation/rack'
gem 'opentelemetry-common', path: '../../../common'
gem 'opentelemetry-sdk', path: '../../../sdk'
gem 'rack'
gem 'rack-test'
