# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-api'
gem 'opentelemetry-common'
gem 'opentelemetry-instrumentation-rack'
gem 'opentelemetry-sdk'
gem 'rack'
gem 'rack-test'
