# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/common/v1/common.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("opentelemetry/proto/common/v1/common.proto", :syntax => :proto3) do
    add_message "opentelemetry.proto.common.v1.AnyValue" do
      oneof :value do
        optional :string_value, :string, 1
        optional :bool_value, :bool, 2
        optional :int_value, :int64, 3
        optional :double_value, :double, 4
        optional :array_value, :message, 5, "opentelemetry.proto.common.v1.ArrayValue"
        optional :kvlist_value, :message, 6, "opentelemetry.proto.common.v1.KeyValueList"
      end
    end
    add_message "opentelemetry.proto.common.v1.ArrayValue" do
      repeated :values, :message, 1, "opentelemetry.proto.common.v1.AnyValue"
    end
    add_message "opentelemetry.proto.common.v1.KeyValueList" do
      repeated :values, :message, 1, "opentelemetry.proto.common.v1.KeyValue"
    end
    add_message "opentelemetry.proto.common.v1.KeyValue" do
      optional :key, :string, 1
      optional :value, :message, 2, "opentelemetry.proto.common.v1.AnyValue"
    end
    add_message "opentelemetry.proto.common.v1.StringKeyValue" do
      optional :key, :string, 1
      optional :value, :string, 2
    end
    add_message "opentelemetry.proto.common.v1.InstrumentationLibrary" do
      optional :name, :string, 1
      optional :version, :string, 2
    end
  end
end

module Opentelemetry
  module Proto
    module Common
      module V1
        AnyValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.common.v1.AnyValue").msgclass
        ArrayValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.common.v1.ArrayValue").msgclass
        KeyValueList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.common.v1.KeyValueList").msgclass
        KeyValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.common.v1.KeyValue").msgclass
        StringKeyValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.common.v1.StringKeyValue").msgclass
        InstrumentationLibrary = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.common.v1.InstrumentationLibrary").msgclass
      end
    end
  end
end
