# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in opentelemetry-rails.gemspec.
gemspec

gem 'opentelemetry-api', path: '../api'
gem 'opentelemetry-common', path: '../common'
gem 'opentelemetry-instrumentation-all', path: '../instrumentation/all'
gem 'opentelemetry-sdk', path: '../sdk'
gem 'opentelemetry-semantic_conventions', path: '../semantic_conventions'

platforms :jruby do
  gem 'activerecord-jdbcsqlite3-adapter'
end

gem 'sqlite3', platforms: %I[ruby mswin x64_mingw]
gem 'tzinfo-data', platforms: %I[mswin x64_mingw]

group :development, :test do
  gem 'pry'
end

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
