# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :development, :test do
  # Use opentelemetry-api from source
  gem 'opentelemetry-api', path: '../../api'
end
