inherit_from: ../contrib/rubocop.yml

Bundler/OrderedGems:
  Exclude:
    - gemfiles/**/*
Style/FrozenStringLiteralComment:
  Exclude:
    - gemfiles/**/*
Style/ExplicitBlockArgument:
  Enabled: false
Style/StringLiterals:
  Exclude:
    - gemfiles/**/*
Metrics/BlockLength:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/opentelemetry-common.rb"
