# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'
eval_gemfile File.expand_path('../Gemfile', __dir__)

gemspec

group :development, :test do
  gem 'dotenv', '~> 3.2.0'
  gem 'minitest', '~> 5.27.0'
  gem 'simplecov', '~> 1.1.0'
  gem 'yard', '~> 0.9.0'
  gem 'yard-doctest', '~> 0.1.6'
  # Use the opentelemetry-api gem from source
  gem 'opentelemetry-api', path: '../api', require: false
  gem 'opentelemetry-test-helpers', path: '../test_helpers', require: false
  gem 'pry'
end
