# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

(14..23).each do |i|
  version = "3.#{i}"
  appraise "google-protobuf-#{version}" do
    gem 'google-protobuf', "~> #{version}"
  end
end

%w[4.29.0 4.36.1].each do |version|
  appraise "google-protobuf-#{version}" do
    gem 'google-protobuf', "~> #{version}"
  end
end
