# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-adapters-rest-client', path: '../../../adapters/restclient'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-sdk', path: '../../../sdk'
gem 'rest-client'
