# frozen_string_literal: true

# Copyright 2020 OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'active_model_serializers-2.13' do
  gem 'active_model_serializers', '~> 2.13.0'
end
