# frozen_string_literal: true

source "https://rubygems.org"

gem "faraday", "~> 2.0"
gem "opentelemetry-api"
gem "opentelemetry-common"
gem "opentelemetry-sdk"
gem "sinatra", "~> 4.1"
gem "puma"
gem "rackup"
