# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/metrics/v1/metrics.proto

require 'google/protobuf'

require 'opentelemetry/proto/common/v1/common_pb'
require 'opentelemetry/proto/resource/v1/resource_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("opentelemetry/proto/metrics/v1/metrics.proto", :syntax => :proto3) do
    add_message "opentelemetry.proto.metrics.v1.MetricsData" do
      repeated :resource_metrics, :message, 1, "opentelemetry.proto.metrics.v1.ResourceMetrics"
    end
    add_message "opentelemetry.proto.metrics.v1.ResourceMetrics" do
      optional :resource, :message, 1, "opentelemetry.proto.resource.v1.Resource"
      repeated :scope_metrics, :message, 2, "opentelemetry.proto.metrics.v1.ScopeMetrics"
      optional :schema_url, :string, 3
    end
    add_message "opentelemetry.proto.metrics.v1.ScopeMetrics" do
      optional :scope, :message, 1, "opentelemetry.proto.common.v1.InstrumentationScope"
      repeated :metrics, :message, 2, "opentelemetry.proto.metrics.v1.Metric"
      optional :schema_url, :string, 3
    end
    add_message "opentelemetry.proto.metrics.v1.Metric" do
      optional :name, :string, 1
      optional :description, :string, 2
      optional :unit, :string, 3
      oneof :data do
        optional :gauge, :message, 5, "opentelemetry.proto.metrics.v1.Gauge"
        optional :sum, :message, 7, "opentelemetry.proto.metrics.v1.Sum"
        optional :histogram, :message, 9, "opentelemetry.proto.metrics.v1.Histogram"
        optional :exponential_histogram, :message, 10, "opentelemetry.proto.metrics.v1.ExponentialHistogram"
        optional :summary, :message, 11, "opentelemetry.proto.metrics.v1.Summary"
      end
    end
    add_message "opentelemetry.proto.metrics.v1.Gauge" do
      repeated :data_points, :message, 1, "opentelemetry.proto.metrics.v1.NumberDataPoint"
    end
    add_message "opentelemetry.proto.metrics.v1.Sum" do
      repeated :data_points, :message, 1, "opentelemetry.proto.metrics.v1.NumberDataPoint"
      optional :aggregation_temporality, :enum, 2, "opentelemetry.proto.metrics.v1.AggregationTemporality"
      optional :is_monotonic, :bool, 3
    end
    add_message "opentelemetry.proto.metrics.v1.Histogram" do
      repeated :data_points, :message, 1, "opentelemetry.proto.metrics.v1.HistogramDataPoint"
      optional :aggregation_temporality, :enum, 2, "opentelemetry.proto.metrics.v1.AggregationTemporality"
    end
    add_message "opentelemetry.proto.metrics.v1.ExponentialHistogram" do
      repeated :data_points, :message, 1, "opentelemetry.proto.metrics.v1.ExponentialHistogramDataPoint"
      optional :aggregation_temporality, :enum, 2, "opentelemetry.proto.metrics.v1.AggregationTemporality"
    end
    add_message "opentelemetry.proto.metrics.v1.Summary" do
      repeated :data_points, :message, 1, "opentelemetry.proto.metrics.v1.SummaryDataPoint"
    end
    add_message "opentelemetry.proto.metrics.v1.NumberDataPoint" do
      repeated :attributes, :message, 7, "opentelemetry.proto.common.v1.KeyValue"
      optional :start_time_unix_nano, :fixed64, 2
      optional :time_unix_nano, :fixed64, 3
      repeated :exemplars, :message, 5, "opentelemetry.proto.metrics.v1.Exemplar"
      optional :flags, :uint32, 8
      oneof :value do
        optional :as_double, :double, 4
        optional :as_int, :sfixed64, 6
      end
    end
    add_message "opentelemetry.proto.metrics.v1.HistogramDataPoint" do
      repeated :attributes, :message, 9, "opentelemetry.proto.common.v1.KeyValue"
      optional :start_time_unix_nano, :fixed64, 2
      optional :time_unix_nano, :fixed64, 3
      optional :count, :fixed64, 4
      proto3_optional :sum, :double, 5
      repeated :bucket_counts, :fixed64, 6
      repeated :explicit_bounds, :double, 7
      repeated :exemplars, :message, 8, "opentelemetry.proto.metrics.v1.Exemplar"
      optional :flags, :uint32, 10
      proto3_optional :min, :double, 11
      proto3_optional :max, :double, 12
    end
    add_message "opentelemetry.proto.metrics.v1.ExponentialHistogramDataPoint" do
      repeated :attributes, :message, 1, "opentelemetry.proto.common.v1.KeyValue"
      optional :start_time_unix_nano, :fixed64, 2
      optional :time_unix_nano, :fixed64, 3
      optional :count, :fixed64, 4
      proto3_optional :sum, :double, 5
      optional :scale, :sint32, 6
      optional :zero_count, :fixed64, 7
      optional :positive, :message, 8, "opentelemetry.proto.metrics.v1.ExponentialHistogramDataPoint.Buckets"
      optional :negative, :message, 9, "opentelemetry.proto.metrics.v1.ExponentialHistogramDataPoint.Buckets"
      optional :flags, :uint32, 10
      repeated :exemplars, :message, 11, "opentelemetry.proto.metrics.v1.Exemplar"
      proto3_optional :min, :double, 12
      proto3_optional :max, :double, 13
      optional :zero_threshold, :double, 14
    end
    add_message "opentelemetry.proto.metrics.v1.ExponentialHistogramDataPoint.Buckets" do
      optional :offset, :sint32, 1
      repeated :bucket_counts, :uint64, 2
    end
    add_message "opentelemetry.proto.metrics.v1.SummaryDataPoint" do
      repeated :attributes, :message, 7, "opentelemetry.proto.common.v1.KeyValue"
      optional :start_time_unix_nano, :fixed64, 2
      optional :time_unix_nano, :fixed64, 3
      optional :count, :fixed64, 4
      optional :sum, :double, 5
      repeated :quantile_values, :message, 6, "opentelemetry.proto.metrics.v1.SummaryDataPoint.ValueAtQuantile"
      optional :flags, :uint32, 8
    end
    add_message "opentelemetry.proto.metrics.v1.SummaryDataPoint.ValueAtQuantile" do
      optional :quantile, :double, 1
      optional :value, :double, 2
    end
    add_message "opentelemetry.proto.metrics.v1.Exemplar" do
      repeated :filtered_attributes, :message, 7, "opentelemetry.proto.common.v1.KeyValue"
      optional :time_unix_nano, :fixed64, 2
      optional :span_id, :bytes, 4
      optional :trace_id, :bytes, 5
      oneof :value do
        optional :as_double, :double, 3
        optional :as_int, :sfixed64, 6
      end
    end
    add_enum "opentelemetry.proto.metrics.v1.AggregationTemporality" do
      value :AGGREGATION_TEMPORALITY_UNSPECIFIED, 0
      value :AGGREGATION_TEMPORALITY_DELTA, 1
      value :AGGREGATION_TEMPORALITY_CUMULATIVE, 2
    end
    add_enum "opentelemetry.proto.metrics.v1.DataPointFlags" do
      value :DATA_POINT_FLAGS_DO_NOT_USE, 0
      value :DATA_POINT_FLAGS_NO_RECORDED_VALUE_MASK, 1
    end
  end
end

module Opentelemetry
  module Proto
    module Metrics
      module V1
        MetricsData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.MetricsData").msgclass
        ResourceMetrics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.ResourceMetrics").msgclass
        ScopeMetrics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.ScopeMetrics").msgclass
        Metric = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.Metric").msgclass
        Gauge = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.Gauge").msgclass
        Sum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.Sum").msgclass
        Histogram = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.Histogram").msgclass
        ExponentialHistogram = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.ExponentialHistogram").msgclass
        Summary = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.Summary").msgclass
        NumberDataPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.NumberDataPoint").msgclass
        HistogramDataPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.HistogramDataPoint").msgclass
        ExponentialHistogramDataPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.ExponentialHistogramDataPoint").msgclass
        ExponentialHistogramDataPoint::Buckets = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.ExponentialHistogramDataPoint.Buckets").msgclass
        SummaryDataPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.SummaryDataPoint").msgclass
        SummaryDataPoint::ValueAtQuantile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.SummaryDataPoint.ValueAtQuantile").msgclass
        Exemplar = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.Exemplar").msgclass
        AggregationTemporality = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.AggregationTemporality").enummodule
        DataPointFlags = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.metrics.v1.DataPointFlags").enummodule
      end
    end
  end
end
