# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-adapters-sidekiq', path: '../../../adapters/sidekiq'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-sdk', path: '../../../sdk'
