inherit_from: ../contrib/rubocop.yml

Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 50
Metrics/PerceivedComplexity:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 20

Naming/FileName:
  Exclude:
    - "lib/opentelemetry-sdk-experimental.rb"
Naming/MethodParameterName:
  Enabled: false
