# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

gem 'opentelemetry-api', path: '../../api'
gem 'opentelemetry-instrumentation-base', path: '../base'
gem 'opentelemetry-registry', path: '../../registry'

group :test do
  gem 'byebug'
  gem 'opentelemetry-common', path: '../../common'
  gem 'opentelemetry-sdk', path: '../../sdk'
  gem 'opentelemetry-semantic_conventions', path: '../../semantic_conventions'
  gem 'opentelemetry-test-helpers', path: '../../test_helpers'
  gem 'pry-byebug'
  gem 'sqlite3-ruby'
end
