# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
# This file was autogenerated. Do not edit it by hand.

module OpenTelemetry
  module SemanticCandidates
    module FILE 
      # @!group Attribute Names
    
      # Directory where the file is located. It should include the drive letter, when appropriate
      #
      # @note StabilityLevel.EXPERIMENTAL
      FILE_DIRECTORY = 'file.directory'
    
      # File extension, excluding the leading dot
      #
      # When the file name has multiple extensions (example.tar.gz), only the last one should be captured ("gz", not "tar.gz")
      #
      # @note StabilityLevel.EXPERIMENTAL
      FILE_EXTENSION = 'file.extension'
    
      # Name of the file including the extension, without the directory
      #
      # @note StabilityLevel.EXPERIMENTAL
      FILE_NAME = 'file.name'
    
      # Full path to the file, including the file name. It should include the drive letter, when appropriate
      #
      # @note StabilityLevel.EXPERIMENTAL
      FILE_PATH = 'file.path'
    
      # File size in bytes
      #
      # @note StabilityLevel.EXPERIMENTAL
      FILE_SIZE = 'file.size'
    
      # @!endgroup
    end
  end
end