# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
# This file was autogenerated. Do not edit it by hand.

module OpenTelemetry
  module SemanticCandidates
    module USER_AGENT 
      # @!group Attribute Names
    
      # Name of the user-agent extracted from original. Usually refers to the browser's name
      #
      # [Example](https://www.whatsmyua.info) of extracting browser's name from original string. In the case of using a user-agent for non-browser products, such as microservices with multiple names/versions inside the `user_agent.original`, the most significant name SHOULD be selected. In such a scenario it should align with `user_agent.version`
      #
      # @note StabilityLevel.EXPERIMENTAL
      USER_AGENT_NAME = 'user_agent.name'
    
      # Value of the [HTTP User-Agent](https://www.rfc-editor.org/rfc/rfc9110.html#field.user-agent) header sent by the client
      #
      # @note StabilityLevel.STABLE
      #
      # @deprecated Now available in the stable namespace at {OpenTelemetry::SemanticConventions::USER_AGENT::ORIGINAL}.
      USER_AGENT_ORIGINAL = 'user_agent.original'
    
      # Version of the user-agent extracted from original. Usually refers to the browser's version
      #
      # [Example](https://www.whatsmyua.info) of extracting browser's version from original string. In the case of using a user-agent for non-browser products, such as microservices with multiple names/versions inside the `user_agent.original`, the most significant version SHOULD be selected. In such a scenario it should align with `user_agent.name`
      #
      # @note StabilityLevel.EXPERIMENTAL
      USER_AGENT_VERSION = 'user_agent.version'
    
      # @!endgroup
    end
  end
end