# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport'
gem 'opentelemetry-api'
gem 'opentelemetry-common'
gem 'opentelemetry-instrumentation-active_support'
gem 'opentelemetry-sdk'
