#
# Autogenerated by Thrift Compiler (0.12.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'jaeger_types'
require 'zipkincore_types'


module OpenTelemetry
  module Exporter
    module Jaeger
      module Thrift
      end
    end
  end
end
