# frozen_string_literal: true

# Copyright 2019 OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gem 'opentelemetry-api', path: '../../api'
gem 'opentelemetry-sdk', path: '../../sdk'

gemspec
