# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/trace/v1/trace.proto

require 'google/protobuf'

require 'opentelemetry/proto/common/v1/common_pb'
require 'opentelemetry/proto/resource/v1/resource_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("opentelemetry/proto/trace/v1/trace.proto", :syntax => :proto3) do
    add_message "opentelemetry.proto.trace.v1.TracesData" do
      repeated :resource_spans, :message, 1, "opentelemetry.proto.trace.v1.ResourceSpans"
    end
    add_message "opentelemetry.proto.trace.v1.ResourceSpans" do
      optional :resource, :message, 1, "opentelemetry.proto.resource.v1.Resource"
      repeated :scope_spans, :message, 2, "opentelemetry.proto.trace.v1.ScopeSpans"
      optional :schema_url, :string, 3
    end
    add_message "opentelemetry.proto.trace.v1.ScopeSpans" do
      optional :scope, :message, 1, "opentelemetry.proto.common.v1.InstrumentationScope"
      repeated :spans, :message, 2, "opentelemetry.proto.trace.v1.Span"
      optional :schema_url, :string, 3
    end
    add_message "opentelemetry.proto.trace.v1.Span" do
      optional :trace_id, :bytes, 1
      optional :span_id, :bytes, 2
      optional :trace_state, :string, 3
      optional :parent_span_id, :bytes, 4
      optional :name, :string, 5
      optional :kind, :enum, 6, "opentelemetry.proto.trace.v1.Span.SpanKind"
      optional :start_time_unix_nano, :fixed64, 7
      optional :end_time_unix_nano, :fixed64, 8
      repeated :attributes, :message, 9, "opentelemetry.proto.common.v1.KeyValue"
      optional :dropped_attributes_count, :uint32, 10
      repeated :events, :message, 11, "opentelemetry.proto.trace.v1.Span.Event"
      optional :dropped_events_count, :uint32, 12
      repeated :links, :message, 13, "opentelemetry.proto.trace.v1.Span.Link"
      optional :dropped_links_count, :uint32, 14
      optional :status, :message, 15, "opentelemetry.proto.trace.v1.Status"
    end
    add_message "opentelemetry.proto.trace.v1.Span.Event" do
      optional :time_unix_nano, :fixed64, 1
      optional :name, :string, 2
      repeated :attributes, :message, 3, "opentelemetry.proto.common.v1.KeyValue"
      optional :dropped_attributes_count, :uint32, 4
    end
    add_message "opentelemetry.proto.trace.v1.Span.Link" do
      optional :trace_id, :bytes, 1
      optional :span_id, :bytes, 2
      optional :trace_state, :string, 3
      repeated :attributes, :message, 4, "opentelemetry.proto.common.v1.KeyValue"
      optional :dropped_attributes_count, :uint32, 5
    end
    add_enum "opentelemetry.proto.trace.v1.Span.SpanKind" do
      value :SPAN_KIND_UNSPECIFIED, 0
      value :SPAN_KIND_INTERNAL, 1
      value :SPAN_KIND_SERVER, 2
      value :SPAN_KIND_CLIENT, 3
      value :SPAN_KIND_PRODUCER, 4
      value :SPAN_KIND_CONSUMER, 5
    end
    add_message "opentelemetry.proto.trace.v1.Status" do
      optional :message, :string, 2
      optional :code, :enum, 3, "opentelemetry.proto.trace.v1.Status.StatusCode"
    end
    add_enum "opentelemetry.proto.trace.v1.Status.StatusCode" do
      value :STATUS_CODE_UNSET, 0
      value :STATUS_CODE_OK, 1
      value :STATUS_CODE_ERROR, 2
    end
  end
end

module Opentelemetry
  module Proto
    module Trace
      module V1
        TracesData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.trace.v1.TracesData").msgclass
        ResourceSpans = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.trace.v1.ResourceSpans").msgclass
        ScopeSpans = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.trace.v1.ScopeSpans").msgclass
        Span = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.trace.v1.Span").msgclass
        Span::Event = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.trace.v1.Span.Event").msgclass
        Span::Link = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.trace.v1.Span.Link").msgclass
        Span::SpanKind = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.trace.v1.Span.SpanKind").enummodule
        Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.trace.v1.Status").msgclass
        Status::StatusCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.trace.v1.Status.StatusCode").enummodule
      end
    end
  end
end
