# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/trace/v1/trace_config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("opentelemetry/proto/trace/v1/trace_config.proto", :syntax => :proto3) do
    add_message "opentelemetry.proto.trace.v1.TraceConfig" do
      optional :max_number_of_attributes, :int64, 4
      optional :max_number_of_timed_events, :int64, 5
      optional :max_number_of_attributes_per_timed_event, :int64, 6
      optional :max_number_of_links, :int64, 7
      optional :max_number_of_attributes_per_link, :int64, 8
      oneof :sampler do
        optional :constant_sampler, :message, 1, "opentelemetry.proto.trace.v1.ConstantSampler"
        optional :trace_id_ratio_based, :message, 2, "opentelemetry.proto.trace.v1.TraceIdRatioBased"
        optional :rate_limiting_sampler, :message, 3, "opentelemetry.proto.trace.v1.RateLimitingSampler"
      end
    end
    add_message "opentelemetry.proto.trace.v1.ConstantSampler" do
      optional :decision, :enum, 1, "opentelemetry.proto.trace.v1.ConstantSampler.ConstantDecision"
    end
    add_enum "opentelemetry.proto.trace.v1.ConstantSampler.ConstantDecision" do
      value :ALWAYS_OFF, 0
      value :ALWAYS_ON, 1
      value :ALWAYS_PARENT, 2
    end
    add_message "opentelemetry.proto.trace.v1.TraceIdRatioBased" do
      optional :samplingRatio, :double, 1
    end
    add_message "opentelemetry.proto.trace.v1.RateLimitingSampler" do
      optional :qps, :int64, 1
    end
  end
end

module Opentelemetry
  module Proto
    module Trace
      module V1
        TraceConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.trace.v1.TraceConfig").msgclass
        ConstantSampler = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.trace.v1.ConstantSampler").msgclass
        ConstantSampler::ConstantDecision = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.trace.v1.ConstantSampler.ConstantDecision").enummodule
        TraceIdRatioBased = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.trace.v1.TraceIdRatioBased").msgclass
        RateLimitingSampler = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.trace.v1.RateLimitingSampler").msgclass
      end
    end
  end
end
