inherit_from: ../contrib/rubocop.yml

Lint/EmptyClass:
  Exclude:
    - 'test/opentelemetry/sdk/logs/export/batch_log_record_processor_test.rb'

Metrics/MethodLength:
  Max: 23
Metrics/PerceivedComplexity:
  Max: 10
Metrics/CyclomaticComplexity:
  Max: 10
Minitest/AssertWithExpectedArgument:
  Enabled: false
Minitest/UselessAssertion:
  Enabled: false
