# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

eval_gemfile '../Gemfile'

group :test, :development do
  gem 'minitest', '~> 5.27.0'
  gem 'yard', '~> 0.9.0'
  gem 'yard-doctest', '~> 0.1.17'
  gem 'opentelemetry-api', path: '../api', require: false
  gem 'opentelemetry-exporter-otlp-logs', path: '../exporter/otlp-logs', require: false
  gem 'opentelemetry-logs-api', path: '../logs_api', require: false
  gem 'opentelemetry-sdk', path: '../sdk', require: false
  gem 'opentelemetry-test-helpers', path: '../test_helpers', require: false
end
