# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'aws-sdk-3.1' do
  gem 'aws-sdk', '~> 3.1'
end

appraise 'aws-sdk-3.0' do
  gem 'aws-sdk', '~> 3.0'
end
