# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'webrick', '~> 1.7'
end
