AllCops:
  TargetRubyVersion: '2.4.0'

Metrics/CyclomaticComplexity:
  Max: 7
Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Style/ModuleFunction:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
