AllCops:
  TargetRubyVersion: '2.4.0'

Metrics/AbcSize:
  Max: 18
Metrics/LineLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Style/ModuleFunction:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
