# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

eval_gemfile '../Gemfile'

group :test, :development do
  gem 'opentelemetry-instrumentation-base', '~> 0.26.0'
  gem 'minitest', '~> 5.27.0'
  gem 'yard', '~> 0.9.0'
  gem 'yard-doctest', '~> 0.1.6'
  gem 'opentelemetry-api', path: '../api', require: false
  gem 'opentelemetry-common', path: '../common', require: false
  gem 'opentelemetry-exporter-zipkin', path: '../exporter/zipkin', require: false
  gem 'opentelemetry-registry', path: '../registry', require: false
  gem 'opentelemetry-semantic_conventions', path: '../semantic_conventions', require: false
  gem 'opentelemetry-test-helpers', path: '../test_helpers', require: false
end
