# frozen_string_literal: true

source 'https://rubygems.org'

gem 'faraday'
gem 'opentelemetry-adapters-faraday', path: '../../../adapters/faraday'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-sdk', path: '../../../sdk'
