# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test, :development do
  gem 'minitest', '6.0.6'
  gem 'rake', '13.4.2'
  gem 'rubocop', '1.87.0'
  gem 'rubocop-minitest', '0.39.1'
  gem 'rubocop-performance', '1.26.1'
  gem 'rubocop-rake', '0.7.1'
  gem 'rubocop-rspec', '3.10.2'
  gem 'simplecov', '0.22.0'
  gem 'yard', '0.9.44'

  # Local path overrides for gems developed in this monorepo
  gem 'opentelemetry-api',                       path: '../api',                       require: false
  gem 'opentelemetry-common',                    path: '../common',                    require: false
  gem 'opentelemetry-exporter-otlp',             path: '../exporter/otlp',             require: false
  gem 'opentelemetry-exporter-otlp-common',      path: '../exporter/otlp-common',      require: false
  gem 'opentelemetry-registry',                  path: '../registry',                  require: false
  gem 'opentelemetry-sdk',                       path: '../sdk',                       require: false
  gem 'opentelemetry-test-helpers',              path: '../test_helpers',              require: false

  gem 'opentelemetry-instrumentation-all',                      '0.94.0'
  gem 'opentelemetry-propagator-google_cloud_trace_context',    '0.4.0'
  gem 'opentelemetry-propagator-ottrace',                       '0.25.0'
  gem 'opentelemetry-propagator-xray',                          '0.27.0'
  gem 'opentelemetry-resource-detector-aws',                    '0.7.0'
  gem 'opentelemetry-resource-detector-azure',                  '0.4.0'
  gem 'opentelemetry-resource-detector-container',              '0.4.0'
  gem 'opentelemetry-resource-detector-google_cloud_platform',  '0.4.0'

  # Prevent bundler from downgrading google-protobuf to an incompatible
  # pre-built binary (glibc) that does not run in Alpine (musl) containers.
  gem 'google-protobuf', '3.25.8'

  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'bigdecimal'
    gem 'mutex_m'
  end
  gem 'logger' if RUBY_VERSION >= '4.0.0'
end
