# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport'
gem 'opentelemetry-api'
gem 'opentelemetry-common'
gem 'opentelemetry-instrumentation-ruby_kafka'
gem 'opentelemetry-sdk'
gem 'ruby-kafka'
