# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-common', path: '../../../common'
gem 'opentelemetry-instrumentation-ruby_kafka', path: '../../../instrumentation/ruby_kafka'
gem 'opentelemetry-sdk', path: '../../../sdk'
gem 'ruby-kafka'
