# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-common', path: '../../../common'
gem 'opentelemetry-instrumentation-sinatra', path: '../../../instrumentation/sinatra'
gem 'opentelemetry-sdk', path: '../../../sdk'
gem 'sinatra'
