# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gem 'activerecord', '~> 6.0'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-common', path: '../../../common'
gem 'opentelemetry-instrumentation-que', path: '../../../instrumentation/que'
gem 'opentelemetry-sdk', path: '../../../sdk'
gem 'pg', '~> 1.1'
gem 'que', '~> 1.0.0.beta4'
