# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'manticore-0.7' do
  gem 'manticore', '~> 0.7.1'
end

appraise 'manticore-0.6' do
  gem 'manticore', '~> 0.6.4'
end