# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

gem 'opentelemetry-instrumentation-base', path: '../instrumentation/base'
gem 'opentelemetry-sdk', path: '../sdk'

group :development, :test do
  gem 'byebug'
  gem 'pry'
end
