# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

gem 'opentelemetry-api', path: '../api'
gem 'opentelemetry-common', path: '../common'
gem 'opentelemetry-instrumentation-base', path: '../instrumentation/base'
gem 'opentelemetry-sdk', path: '../sdk'
gem 'opentelemetry-semantic_conventions', path: '../semantic_conventions'

group :development, :test do
  gem 'byebug' unless RUBY_PLATFORM == 'java'
  gem 'pry'
end
