# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :development, :test do
  gem 'byebug' unless RUBY_PLATFORM == 'java'
  gem 'pry'
end
