# frozen_string_literal: true

source 'https://rubygems.org'

gem 'delayed_job'
gem 'opentelemetry-api'
gem 'opentelemetry-common'
gem 'opentelemetry-instrumentation-delayed_job'
gem 'opentelemetry-sdk'
