# frozen_string_literal: true

source 'https://rubygems.org'

gem 'mysql2'
gem 'opentelemetry-adapters-mysql2', path: '../../../adapters/mysql2'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-sdk', path: '../../../sdk'
