# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activejob'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-sdk', path: '../../../sdk'
gem 'opentelemetry-instrumentation-active_job', path: '../../../instrumentation/active_job'
