AllCops:
  TargetRubyVersion: '2.6.0'
  NewCops: enable

Bundler/OrderedGems:
  Exclude:
    - gemfiles/**/*

Gemspec/DevelopmentDependencies:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/TrailingEmptyLines:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/opentelemetry-semantic_conventions.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - gemfiles/**/*
Style/ModuleFunction:
  Enabled: false
Style/StringLiterals:
  Exclude:
    - gemfiles/**/*
