inherit_from: ../contrib/rubocop.yml

AllCops:
  NewCops: enable

Bundler/OrderedGems:
  Exclude:
    - gemfiles/**/*

Gemspec/DevelopmentDependencies:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/TrailingEmptyLines:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/ModuleLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/opentelemetry-semantic_conventions.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - gemfiles/**/*
Style/StringLiterals:
  Exclude:
    - gemfiles/**/*
