services:
  semconv-weaver:
    image: otel/weaver:v0.26.1@sha256:9094862c0ab261bdbcb079bb981f9a573b3659b130a6d2ab8616eca6ba37aaec
    user: "${UID}:${GID}"
    volumes:
      - ./tmp/semconvrepo/model:/source:ro
      - ./templates:/templates:ro
      - ./:/output
    working_dir: /output
    command:
      [
        "registry",
        "generate",
        "--registry=/source",
        "--templates=/templates",
        "ruby",
        "/output/lib/opentelemetry/semconv"
      ]
