services:
  semconv-weaver:
    image: otel/weaver:v0.22.1
    user: "${UID}:${GID}"
    volumes:
      - ./tmp/semconvrepo/model:/source:ro
      - ./templates:/templates:ro
      - ./:/output
    working_dir: /output
    entrypoint: ["registry", "generate"]
    command:
      [
        "--registry=/source",
        "--templates=/templates",
        "ruby",
        "/output/lib/opentelemetry/semconv"
      ]
