# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :development, :test do
  gem 'minitest', '~> 5.27.0'
  gem 'mutex_m' if RUBY_VERSION >= '3.4'
  gem 'rake', '~> 13.3.0'
  gem 'rubocop', '~> 1.75.0'
  gem 'rubocop-minitest', '~> 0.38.0'
  gem 'rubocop-performance', '~> 1.25.0'
  gem 'rubocop-rake', '~> 0.7.1'
  gem 'rubocop-rspec', '~> 3.5.0'
  gem 'simplecov', '~> 0.17.0'
  gem 'yard', '~> 0.9.0'
  gem 'yard-doctest', '~> 0.1.6'
  gem 'opentelemetry-api', path: '../api', require: false
  gem 'pry'
end
