# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'opentelemetry-sdk', path: '../../sdk'
  gem 'opentelemetry-instrumentation-base', path: '../../instrumentation/base'
  gem 'opentelemetry-instrumentation-rack', path: '../../instrumentation/rack'
  gem 'pry-byebug'
end
