# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gem 'opentelemetry-api', path: '../../api'
gem 'opentelemetry-common', path: '../../common'
gem 'opentelemetry-exporter-otlp-common', path: '../../exporter/otlp-common'
gem 'opentelemetry-exporter-otlp', path: '../../exporter/otlp'
gem 'opentelemetry-sdk', path: '../../sdk'
gem 'opentelemetry-config', path: '..'
gem 'opentelemetry-instrumentation-all'
