# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'sinatra-2.1' do
  gem 'sinatra', '2.1.0'
end

appraise 'sinatra-1.4' do
  gem 'sinatra', '1.4.8'
end
