# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

gem "rake", "~> 13.0"
gem "rake-compiler", "~> 1.2"
gem "rb_sys", "~> 0.9"
gem "test-unit"

group :test, :development do
  gem 'pry'
  gem 'benchmark'
  gem 'benchmark-memory'
  gem 'opentelemetry-api', path: '../api'
  gem 'opentelemetry-common', path: '../common'
  gem 'opentelemetry-registry', path: '../registry'
  gem 'opentelemetry-semantic_conventions', path: '../semantic_conventions'
  gem 'opentelemetry-test-helpers', path: '../test_helpers'
end
