# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

# gem "rb_sys", "~> 0.9.44"
# gem "rake"
# gem "rake-compiler", "1.2.0"
# gem "test-unit"

gemspec

group :test, :development do
  gem 'opentelemetry-api', path: '../api'
  gem 'opentelemetry-common', path: '../common'
  gem 'opentelemetry-registry', path: '../registry'
  gem 'opentelemetry-semantic_conventions', path: '../semantic_conventions'
  gem 'opentelemetry-test-helpers', path: '../test_helpers'
end
