# frozen_string_literal: true

require "rake/testtask"
require "rake/extensiontask"

task default: :test

Rake::ExtensionTask.new("opentelemetry_sdk_rust") do |c|
  c.lib_dir = "lib/opentelemetry_sdk_rust"
end

task :dev do
  ENV['RB_SYS_CARGO_PROFILE'] = 'dev'
end

Rake::TestTask.new do |t|
  t.deps << :dev << :compile
  # t.libs << 'test'
  # t.libs << 'lib'
  # t.libs << '../api/lib'
  t.test_files = FileList[File.expand_path("test/*_test.rb", __dir__)]
end
