inherit_from: ../contrib/rubocop.yml

Gemspec/DevelopmentDependencies:
 Enabled: false
Style/EmptyClassDefinition:
  Exclude:
    - 'benchmarks/context_bench.rb'
Style/OneClassPerFile:
  Exclude:
    - 'benchmarks/context_bench.rb'
