inherit_from: ../contrib/rubocop.yml

AllCops:
  Exclude:
    - "benchmarks/context_bench.rb"

Naming/FileName:
  Exclude:
    - "lib/opentelemetry-api.rb"
Style/ExplicitBlockArgument:
  Enabled: false
