# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

eval_gemfile '../contrib/Gemfile.shared'

group :test, :development do
  gem 'opentelemetry-test-helpers', path: '../test_helpers'
end
