name: Build / Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: &path_filters
      - ".docker/**"
      - "docker-compose.yml"
      - ".github/workflows/ci-build-docker.yml"
  pull_request:
    branches:
      - main
    paths: *path_filters
  merge_group:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Combined Docker Compose
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build Docker image
        run: docker compose -f docker-compose.yml up -d
