name: Build / Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: &path_filters
      - ".docker/**"
      - "docker-compose.yml"
      - ".github/workflows/ci-build-docker.yml"
  pull_request:
    branches:
      - main
    paths: *path_filters
  merge_group:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Combined Docker Compose
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Build Docker image
        run: docker compose -f docker-compose.yml up -d
