name: Markdown Lint Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  markdownlint-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # equivalent cli: markdownlint-cli2  "**/*.md" "#**/CHANGELOG.md" "#.github/**" --config .markdownlint.json
      - name: "Markdown Lint Check"
        uses: DavidAnson/markdownlint-cli2-action@8de2aa07cae85fd17c0b35642db70cf5495f1d25 # v24.0.0
        with:
          config: .markdownlint.json
          fix: false
          globs: |
            **/*.md
            !**/CHANGELOG.md
            !.github/**
