name: Review / PR

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
  merge_group:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }} # Ensure that only one instance of this workflow is running per Pull Request or ref
  cancel-in-progress: true # Cancel any previous runs of this workflow

jobs:
  validate-commits:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby' }}
    name: Title
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      # restrict checks to pull requests to avoid issues blocking the merge queue
      - name: Validate PR Title
        if: ${{ github.event_name == 'pull_request' }}
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            release
            revert
            squash
            style
            test
      - name: Extract PR Title
        id: pr
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "Title: $TITLE" > pr_title.md
      - name: Check PR Title spelling
        uses: streetsidesoftware/cspell-action@de2a73e963e7443969755b648a1008f77033c5b2 # v8.4.0
        with:
          config: .cspell.yml
          suggestions: true
          treat_flagged_words_as_errors: true
          incremental_files_only: false
          files: |
            pr_title.md
