name: "[release hook] Update open releases"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-update-open-requests:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby' }}
    permissions:
      contents: write # required for pushing changes
      pull-requests: write # required for updating open release PRs
    runs-on: ubuntu-24.04
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/.toys/release/Gemfile
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Ruby
        uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
        with:
          ruby-version: "4.0.5"
          bundler-cache: true
      - name: Update open releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle exec toys release _onpush --verbose \
            < /dev/null
