name: "[release hook] Update open releases"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-update-open-requests:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby' }}
    permissions:
      contents: write # required for pushing changes
      pull-requests: write # required for updating open release PRs
    runs-on: ubuntu-24.04
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/.toys/release/Gemfile
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Ruby
        uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
        with:
          ruby-version: "4.0.6"
          bundler-cache: true
      - name: Update open releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle exec toys release _onpush --verbose \
            < /dev/null
