name: Open release request

on:
  workflow_dispatch:
    inputs:
      names:
        description: Components to release (leave blank to release all components)
        required: false
        default: ""
  push:
    branches:
      - main
    paths:
      - "semantic_conventions/semconv.yaml"

permissions:
  contents: read

jobs:
  release-request:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby' }}
    permissions:
      contents: write # required for pushing changes
      pull-requests: write # required for creating release PRs
    runs-on: ubuntu-24.04
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/.toys/release/Gemfile
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Ruby
        uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
        with:
          ruby-version: "4.0.6"
          bundler-cache: true
      - name: Create otelbot app token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.OTELBOT_RUBY_CLIENT_ID }}
          private-key: ${{ secrets.OTELBOT_RUBY_PRIVATE_KEY }}
      - name: Determine releases
        id: detect
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "components=opentelemetry-semantic_conventions" >> $GITHUB_OUTPUT
      - name: Open release pull request
        env:
          # Use an app token instead of GITHUB_TOKEN to trigger workflows
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          RELEASE_NAMES: ${{ github.event.inputs.names || steps.detect.outputs.components }}
          TARGET_BRANCH: ${{ github.ref }}
        run: |
          bundle exec toys release request --yes --verbose \
            "--target-branch=$TARGET_BRANCH" \
            $RELEASE_NAMES \
            < /dev/null
