name: "[release hook] Process release"

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  release-process-request:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby' }}
    permissions:
      contents: write # required for creating releases
      pull-requests: write # required for updating label on PR, posting comments
      issues: write # required for creating new issues on failed releases
    runs-on: ubuntu-24.04
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/.toys/release/Gemfile
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install Ruby
        uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
        with:
          ruby-version: "4.0.6"
          bundler-cache: true
      - name: Process release request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          bundle exec toys release _onclosed --verbose \
            "--event-path=${GITHUB_EVENT_PATH}" \
            < /dev/null
