inherit_from: ../../contrib/rubocop.yml

AllCops:
  Exclude:
    - "thrift/**/*"
    - "vendor/**/*"

Bundler/OrderedGems:
  Exclude:
    - gemfiles/**/*
Style/FrozenStringLiteralComment:
  Exclude:
    - gemfiles/**/*
Style/StringLiterals:
  Exclude:
    - gemfiles/**/*
Metrics/BlockLength:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/opentelemetry-exporter-jaeger.rb"
