AllCops:
  TargetRubyVersion: "2.6.0"
  Exclude:
    - "thrift/**/*"
    - "vendor/**/*"

Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 21
Metrics/ParameterLists:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/opentelemetry-exporter-jaeger.rb"
Style/ModuleFunction:
  Enabled: false
