# frozen_string_literal: true

# Copyright 2019 OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

# Use the opentelemetry-api gem from source
gem 'ddtrace', '~> 0.36'
gem 'opentelemetry-api', path: '../../api'
