# frozen_string_literal: true

source 'https://rubygems.org'

gem 'active_model_serializers'
gem 'opentelemetry-api', path: '../../../api'
gem 'opentelemetry-common', path: '../../../common'
gem 'opentelemetry-instrumentation-active_model_serializers', path: '../../../instrumentation/active_model_serializers'
gem 'opentelemetry-sdk', path: '../../../sdk'
